services:
  # 現在只有這一個 Nginx 了
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro # 直接把編譯好的檔案掛載進來
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: always
  backend:
      build: ./backend
      environment:
        - DB_HOST=db
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        - db
      restart: always
  
  db:
      image: postgres:15-alpine
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      restart: always
