limit_req_zone $binary_remote_addr zone=public_api_limit:10m rate=1r/s;

server {
    listen 80;
    server_name jupiterhsu.ddns.net;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name jupiterhsu.ddns.net;

    # SSL 憑證路徑 (這是 Container 內部的路徑)
    ssl_certificate     /etc/nginx/ssl/live/jupiterhsu.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/jupiterhsu.ddns.net/privkey.pem;

    # 安全性優化設定
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    charset utf-8;

    location ^~ /swagger/ {
        proxy_pass http://backend:8080/swagger/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /swagger {
        return 301 /swagger/;
    }

    # 直接從本地路徑讀取前端檔案
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # React 路由必備設定
    }
    # 針對公開通報與查詢 API 的特殊限速路由定義
    location /api/public/ {
        # burst=5 代表允許短暫緩衝 5 個請求，nodelay 代表超過頻率且緩衝滿了就立刻回傳 429 錯誤
        limit_req zone=public_api_limit burst=5 nodelay;

        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 轉發 API 請求給 Go
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
