server {
    listen 80;
    server_name _;

    charset utf-8;
    
    location /swagger/ {
        proxy_pass http://backend:8080/swagger/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 直接從本地路徑讀取前端檔案
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # React 路由必備設定
    }

    # 轉發 API 請求給 Go
    location /api/ {
        proxy_pass http://backend:8080;
        # ... (CORS 設定等)
    }
}
